# Generated by Django 3.0.8 on 2022-04-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
